### PR TITLE
Job based snapshot revert

### PR DESCRIPTION
**Pull request by eugenyk**
Implemented issue #6 - now one can choose when to revert snapshot

### CODE REVIEW

**Comment by eugenyk** [comment]
@Maxhy, am I right, that new pull requests should be done to this repository, not to @justnom 's one?

**Comment by Maxhy** [comment]
Yes that's the right repo :).
Thanks for your PR, looks fine to me but I didn't have time to do proper testing yet that has to be done before merge. Please wait a few more days.

Great evolution btw!

**Comment by eugenyk** [comment]
@Maxhy, is it better to use [jenkins-ci](https://issues.jenkins-ci.org) for new tasks / bugs or issues on github are ok for your plugin?

**Comment by Maxhy** [comment]
Issues on GitHub are the best for now.
I wanted to test and merge your changes but you have a duplicate PR #7 with 3 additional commit. Is your work completed?

**Comment by eugenyk** [comment]
Yes, the both tasks are completed. It's better to test the last pull request and test both pipeline and simple job. The second one is based on the first pull request, that's why I had to make duplicated commits. So, I advise you to see and test the last pull request with all changes made.

**Pull request merged**
