### PR TITLE
Fixes to work with Jenkins 2.89.4

### PR DESCRIPTION
**Pull request by Maxhy**

### CODE REVIEW

**Comment by justnom** [comment]
Thanks Maxime! 

I've no longer have the time to maintain this plugin. Would you like to take over as the plugin owner?

**Comment by Maxhy** [comment]
You're welcome 😄.
Sure I would gladly become the maintainer of this project. Thank you for your offer.

**Comment by Maxhy** [comment]
@justnom I can take over this plugin as the owner as you suggested. My company allow me to work on it sometimes on company time as we are actively using it. Should be a minimal guarantee, for fixes at least ^^.

**Comment by Maxhy** [comment]
ping @justnom

**Comment by justnom** [comment]
Hey @Maxhy, sorry about the delay, I've just sent you an admin invite to
the repo.

**Pull request merged**
